settings:
  title: '服务今天挂了吗？'
  logo: 'Primary Sangfor Logo.png' # image in ./public/ folder
  daysInHistogram: 180 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '暂时还没挂'
  notAllmonitorsOperational: '挂了一部分'
  monitorLabelOperational: '能用'
  monitorLabelNotOperational: '不能用'
  monitorLabelNoData: '没数据'
  dayInHistogramNoData: '没数据'
  dayInHistogramOperational: '没挂'
  dayInHistogramNotOperational: ' 次无响应' # xx incident(s) recorded

monitors:
  - id: utdp # unique identifier
    name: 安服应急响应中心工具分发平台
    description: '平台' # default=empty
    url: 'https://www.msangfor.com/api/hello' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
